# Sometimes there is a risk things might go wrong
# Python will raise an exception
# We can choose what to do with exceptions

def askUser():
    '''ask the user to enter a number'''

if __name__ == '__main__':
    pass